<?php

class ItemChild extends Item
{

  public function getID()
  {
    return parent::getID(); // TODO: Change the autogenerated stub
  }

  public function getToken()
  {
    return parent::getToken();
  }

}